### ISSUE TITLE
Transfer Repo too LAMPS WG

### ISSUE THREAD

**Issue by seanturner** [lamps-wg/RFC5019bis#39]
I thought I could do it, but I think @tadahik you will need to initiate the transfer. Instruction can be found here:
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account
When picking the organization pick "lamps-wg". I'll be on the lookout for the request to accept it.

**Comment by tadahik** [comment]
Finished.
